/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdCarousel: typeof import('./components/AdCarousel.vue')['default']
    AnimatedCircularProgressBar: typeof import('./components/ui/animated-circular-progressbar/AnimatedCircularProgressBar.vue')['default']
    AnimationLayer: typeof import('./components/AnimationLayer.vue')['default']
    AuroraText: typeof import('./components/AuroraText.vue')['default']
    AuthPanel: typeof import('./components/auth/AuthPanel.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./components/chat/ChatMessageList.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    CloseButton: typeof import('./components/CloseButton.vue')['default']
    CPanel: typeof import('./components/chat/CPanel.vue')['default']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    FlickeringGrid: typeof import('./components/ui/flickering-grid/FlickeringGrid.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormCheckRadio: typeof import('./components/FormCheckRadio.vue')['default']
    FormCheckRadioGroup: typeof import('./components/FormCheckRadioGroup.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameCarousel: typeof import('./components/GameCarousel.vue')['default']
    GameLoader: typeof import('./components/GameLoader.vue')['default']
    GlassButton: typeof import('./components/GlassButton.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LiveWin: typeof import('./components/LiveWin.vue')['default']
    LiveWinItem: typeof import('./components/LiveWinItem.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    Notification: typeof import('./components/common/Notification.vue')['default']
    OverlayLayer: typeof import('./components/OverlayLayer.vue')['default']
    PlayerAvatar: typeof import('./components/PlayerAvatar.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RtgGameLauncher: typeof import('./components/RtgGameLauncher.vue')['default']
    RtgGameLoader: typeof import('./components/RtgGameLoader.vue')['default']
    SettingsButton: typeof import('./components/ui/SettingsButton.vue')['default']
    SettingsView: typeof import('./components/SettingsView.vue')['default']
    SparklesSprite: typeof import('./components/SparklesSprite.vue')['default']
    SpriteAnimator: typeof import('./components/SpriteAnimator.vue')['default']
    StarBurst: typeof import('./components/StarBurst.vue')['default']
    Starfield: typeof import('./components/Starfield.vue')['default']
  }
}
